name: 02-01-Simple Workflow
on: workflow_dispatch
#jobs: 

#on: 
 # schedule:
  #  - cron: '*/5 * * * *'
jobs: 
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test WorkFlow"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
         name:checkout code
         
      - uses: actions/setup-java@v4   
         name:java
  
